"""Payroll Schemas Package"""

from app.schemas.payroll.salary_component import (
    SalaryComponentBase,
    SalaryComponentCreate,
    SalaryComponentUpdate,
    SalaryComponentResponse,
    SalaryComponentList,
    SalaryStructureBase,
    SalaryStructureCreate,
    SalaryStructureUpdate,
    SalaryStructureResponse,
    SalaryStructureList,
    SalaryStructureComponentCreate,
    SalaryStructureComponentResponse,
    EmployeeSalaryBase,
    EmployeeSalaryCreate,
    EmployeeSalaryUpdate,
    EmployeeSalaryResponse,
    EmployeeSalaryList,
    EmployeeSalaryComponentCreate,
    EmployeeSalaryComponentResponse,
)
from app.schemas.payroll.payroll import (
    StatutorySetupBase,
    StatutorySetupCreate,
    StatutorySetupUpdate,
    StatutorySetupResponse,
    PayrollBatchBase,
    PayrollBatchCreate,
    PayrollBatchUpdate,
    PayrollBatchResponse,
    PayrollBatchList,
    PayrollProcessRequest,
    PayrollApproveRequest,
    PayslipBase,
    PayslipResponse,
    PayslipList,
    PayslipUpdate,
    PayslipComponentResponse,
    PayrollStatutoryResponse,
    PayslipGeneratePDF,
)

__all__ = [
    # Salary Components
    "SalaryComponentBase",
    "SalaryComponentCreate",
    "SalaryComponentUpdate",
    "SalaryComponentResponse",
    "SalaryComponentList",
    # Salary Structure
    "SalaryStructureBase",
    "SalaryStructureCreate",
    "SalaryStructureUpdate",
    "SalaryStructureResponse",
    "SalaryStructureList",
    "SalaryStructureComponentCreate",
    "SalaryStructureComponentResponse",
    # Employee Salary
    "EmployeeSalaryBase",
    "EmployeeSalaryCreate",
    "EmployeeSalaryUpdate",
    "EmployeeSalaryResponse",
    "EmployeeSalaryList",
    "EmployeeSalaryComponentCreate",
    "EmployeeSalaryComponentResponse",
    # Statutory
    "StatutorySetupBase",
    "StatutorySetupCreate",
    "StatutorySetupUpdate",
    "StatutorySetupResponse",
    # Payroll Batch
    "PayrollBatchBase",
    "PayrollBatchCreate",
    "PayrollBatchUpdate",
    "PayrollBatchResponse",
    "PayrollBatchList",
    "PayrollProcessRequest",
    "PayrollApproveRequest",
    # Payslip
    "PayslipBase",
    "PayslipResponse",
    "PayslipList",
    "PayslipUpdate",
    "PayslipComponentResponse",
    "PayrollStatutoryResponse",
    "PayslipGeneratePDF",
]
