"""Lending module schemas package."""

# Entity/Borrower Schemas
from app.schemas.lending.entity import (
    # Entity
    EntityBase,
    EntityCreate,
    EntityUpdate,
    EntityResponse,
    EntityListResponse,
    EntityDetailResponse,
    # Contact
    EntityContactCreate,
    EntityContactUpdate,
    EntityContactResponse,
    # Address
    EntityAddressCreate,
    EntityAddressUpdate,
    EntityAddressResponse,
    # Bank Account
    EntityBankAccountCreate,
    EntityBankAccountUpdate,
    EntityBankAccountResponse,
    # Relation
    EntityRelationCreate,
    EntityRelationUpdate,
    EntityRelationResponse,
    # Financial
    EntityFinancialCreate,
    EntityFinancialUpdate,
    EntityFinancialResponse,
)

# KYC Schemas
from app.schemas.lending.kyc import (
    # KYC Document Type
    KYCDocumentTypeCreate,
    KYCDocumentTypeUpdate,
    KYCDocumentTypeResponse,
    # Entity KYC Document
    EntityKYCDocumentCreate,
    EntityKYCDocumentUpdate,
    EntityKYCDocumentResponse,
    # CKYC Transaction
    CKYCSearchRequest,
    CKYCDownloadRequest,
    CKYCTransactionResponse,
    # Bureau Pull
    BureauPullRequest,
    BureauPullResponse,
    BureauReportResponse,
)

# Rating Schemas
from app.schemas.lending.rating import (
    # Risk Category
    RiskCategoryCreate,
    RiskCategoryUpdate,
    RiskCategoryResponse,
    # Risk Parameter
    RiskParameterCreate,
    RiskParameterUpdate,
    RiskParameterResponse,
    # Rating Matrix
    RatingMatrixCreate,
    RatingMatrixUpdate,
    RatingMatrixResponse,
    # Entity Rating
    EntityRatingCreate,
    EntityRatingUpdate,
    EntityRatingResponse,
    EntityRatingDetailResponse,
    # Rating Score Detail
    RatingScoreDetailCreate,
    RatingScoreDetailResponse,
)

# Product Schemas
from app.schemas.lending.product import (
    # Loan Product
    LoanProductCreate,
    LoanProductUpdate,
    LoanProductResponse,
    LoanProductListResponse,
    LoanProductDetailResponse,
    # Interest Rate
    InterestRateCreate,
    InterestRateUpdate,
    InterestRateResponse,
    # Fee Master
    FeeMasterCreate,
    FeeMasterUpdate,
    FeeMasterResponse,
    # Product Fee
    ProductFeeCreate,
    ProductFeeUpdate,
    ProductFeeResponse,
    # Document Checklist
    DocumentChecklistCreate,
    DocumentChecklistUpdate,
    DocumentChecklistResponse,
)

# Application Schemas
from app.schemas.lending.application import (
    # Loan Application
    LoanApplicationCreate,
    LoanApplicationUpdate,
    LoanApplicationResponse,
    LoanApplicationListResponse,
    LoanApplicationDetailResponse,
    # Application Document
    ApplicationDocumentCreate,
    ApplicationDocumentUpdate,
    ApplicationDocumentResponse,
    # Application Fee
    ApplicationFeeCreate,
    ApplicationFeeUpdate,
    ApplicationFeeResponse,
    # Technical Appraisal
    TechnicalAppraisalCreate,
    TechnicalAppraisalUpdate,
    TechnicalAppraisalResponse,
    # Financial Analysis
    FinancialAnalysisCreate,
    FinancialAnalysisUpdate,
    FinancialAnalysisResponse,
    # Project Milestone
    ProjectMilestoneCreate,
    ProjectMilestoneUpdate,
    ProjectMilestoneResponse,
)

# Sanction Schemas
from app.schemas.lending.sanction import (
    # Loan Sanction
    LoanSanctionCreate,
    LoanSanctionUpdate,
    LoanSanctionResponse,
    LoanSanctionDetailResponse,
    # Sanction Condition
    SanctionConditionCreate,
    SanctionConditionUpdate,
    SanctionConditionResponse,
    # Loan Security
    LoanSecurityCreate,
    LoanSecurityUpdate,
    LoanSecurityResponse,
)

# Phase 2: Loan Account Schemas
from app.schemas.lending.loan_account import (
    # Loan Account
    LoanAccountCreate,
    LoanAccountUpdate,
    LoanAccountResponse,
    LoanAccountListResponse,
    LoanAccountDetailResponse,
    # Disbursement
    DisbursementCreate,
    DisbursementUpdate,
    DisbursementResponse,
    DisbursementApproval,
    DisbursementProcess,
    # Repayment Schedule
    RepaymentScheduleCreate,
    RepaymentScheduleResponse,
    RepaymentScheduleDetailResponse,
    ScheduleInstallmentResponse,
    # Loan Receipt
    LoanReceiptCreate,
    LoanReceiptUpdate,
    LoanReceiptResponse,
    LoanReceiptDetailResponse,
    ReceiptAllocationCreate,
    ReceiptAllocationResponse,
    ReceiptBounceRequest,
    # Loan Mandate
    LoanMandateCreate,
    LoanMandateUpdate,
    LoanMandateResponse,
    MandateRegisterRequest,
    MandateCancelRequest,
    # Asset Classification History
    AssetClassificationHistoryCreate,
    AssetClassificationHistoryResponse,
    # Loan Provision
    LoanProvisionCreate,
    LoanProvisionResponse,
    # Loan Adjustment
    LoanAdjustmentCreate,
    LoanAdjustmentResponse,
    # Accrual
    LoanAccrualResponse,
    # Summary
    LoanAccountSummary,
    DPDBucket,
    CollectionSummary,
    DisbursementSummary,
)

# Phase 3: NPA & Collections Schemas
from app.schemas.lending.collections import (
    # Collection Follow-Up
    CollectionFollowUpCreate,
    CollectionFollowUpUpdate,
    CollectionFollowUpExecute,
    CollectionFollowUpResponse,
    # Demand Notice
    DemandNoticeCreate,
    DemandNoticeUpdate,
    DemandNoticeResponse,
    # NPA Record
    NPARecordCreate,
    NPARecordUpdate,
    NPARecordResponse,
    # Penal Interest
    PenalInterestCreate,
    PenalInterestResponse,
    # Penal Waiver
    PenalWaiverCreate,
    PenalWaiverApprove,
    PenalWaiverResponse,
    # OTS Proposal
    OTSProposalCreate,
    OTSProposalUpdate,
    OTSProposalApprove,
    OTSBorrowerAccept,
    OTSPaymentScheduleCreate,
    OTSPaymentScheduleResponse,
    OTSProposalResponse,
    # Loan Restructure
    LoanRestructureCreate,
    LoanRestructureUpdate,
    LoanRestructureApprove,
    LoanRestructureImplement,
    LoanRestructureResponse,
    # Legal Case
    LegalCaseCreate,
    LegalCaseUpdate,
    LegalCaseResponse,
    # Legal Hearing
    LegalHearingCreate,
    LegalHearingUpdate,
    LegalHearingResponse,
    # Property Auction
    PropertyAuctionCreate,
    PropertyAuctionUpdate,
    PropertyAuctionResponse,
    # Write-Off
    WriteOffCreate,
    WriteOffApprove,
    WriteOffEffect,
    WriteOffResponse,
    # Summary
    NPASummary,
    CollectionActivitySummary,
    RecoverySummary,
    # Paginated Responses
    PaginatedFollowUpResponse,
    PaginatedDemandNoticeResponse,
    PaginatedNPARecordResponse,
    PaginatedOTSProposalResponse,
    PaginatedRestructureResponse,
    PaginatedLegalCaseResponse,
    PaginatedAuctionResponse,
    PaginatedWriteOffResponse,
)

# Phase 5: NACH Integration Schemas
from app.schemas.lending.nach import (
    # NACH Batch
    NachBatchBase,
    NachBatchCreate,
    NachBatchGenerateRequest,
    NachBatchUpdate,
    NachBatchSubmit,
    NachBatchResponseUpload,
    NachBatchResponse,
    NachBatchDetailResponse,
    NachBatchListResponse,
    # NACH Transaction
    NachTransactionBase,
    NachTransactionCreate,
    NachTransactionUpdate,
    NachTransactionBulkStatusUpdate,
    NachTransactionResponse,
    NachTransactionDetailResponse,
    NachTransactionListResponse,
    NachTransactionSummary,
    # NACH Mandate Log
    NachMandateLogCreate,
    NachMandateLogUpdate,
    NachMandateLogResponse,
    # Mandate Registration
    MandateRegistrationRequest,
    MandateRegistrationResponse,
    MandateCancellationRequest,
    # Statistics & Reports
    NachBatchStatistics,
    NachMonthlyReport,
    NachBounceAnalysis,
    NachRetryDue,
    NachRetryDueList,
    # File Generation
    NachFileGenerationRequest,
    NachFileGenerationResponse,
    NachResponseFileParseRequest,
    NachResponseFileParseResponse,
)

# Phase 6: Account Aggregator Integration Schemas
from app.schemas.lending.aa import (
    # AA Consent
    AAConsentBase,
    AAConsentCreate,
    AAConsentUpdate,
    AAConsentResponse,
    AAConsentDetailResponse,
    AAConsentListResponse,
    AAConsentRequestInitiate,
    AAConsentInitiateResponse,
    AAConsentRevokeRequest,
    # AA Fetch Session
    AAFetchSessionBase,
    AAFetchSessionCreate,
    AAFetchSessionUpdate,
    AAFetchSessionResponse,
    AAFetchSessionDetailResponse,
    AAFetchSessionListResponse,
    AAFetchDataRequest,
    AAFetchDataResponse,
    # AA Bank Account
    AABankAccountBase,
    AABankAccountCreate,
    AABankAccountResponse,
    AABankAccountDetailResponse,
    AABankAccountListResponse,
    # AA Bank Transaction
    AABankTransactionBase,
    AABankTransactionCreate,
    AABankTransactionResponse,
    AABankTransactionListResponse,
    # AA Consent Log
    AAConsentLogBase,
    AAConsentLogCreate,
    AAConsentLogResponse,
    AAConsentLogListResponse,
    # AA Analytics
    AAConsentStatistics,
    AAFetchStatistics,
    AABankStatementAnalysis,
    AADataImportRequest,
    AADataImportResponse,
    # AA Provider Config
    AAProviderConfig,
    AAProviderHealthCheck,
    # AA Webhooks
    AAWebhookNotification,
    AAConsentStatusWebhook,
    AAFINotificationWebhook,
)

# Phase 4: Treasury & ALM Schemas
from app.schemas.lending.treasury import (
    # Lender
    LenderCreate,
    LenderUpdate,
    LenderResponse,
    LenderListResponse,
    # Borrowing
    BorrowingCreate,
    BorrowingUpdate,
    BorrowingResponse,
    BorrowingListResponse,
    BorrowingDetailResponse,
    # Borrowing Tranche
    BorrowingTrancheCreate,
    BorrowingTrancheApprove,
    BorrowingTrancheDisbursement,
    BorrowingTrancheResponse,
    BorrowingTrancheListResponse,
    # Borrowing Schedule
    BorrowingScheduleResponse,
    BorrowingScheduleListResponse,
    # Borrowing Payment
    BorrowingPaymentCreate,
    BorrowingPaymentResponse,
    BorrowingPaymentListResponse,
    # Borrowing Covenant
    BorrowingCovenantCreate,
    BorrowingCovenantUpdate,
    BorrowingCovenantResponse,
    BorrowingCovenantListResponse,
    # ALM Position
    ALMPositionGenerate,
    ALMPositionResponse,
    ALMPositionListResponse,
    ALMPositionDetailResponse,
    ALMAssetResponse,
    ALMLiabilityResponse,
    # IRS Analysis
    IRSAnalysisGenerate,
    IRSAnalysisResponse,
    IRSAnalysisListResponse,
    # Exposure Limit
    ExposureLimitCreate,
    ExposureLimitUpdate,
    ExposureLimitResponse,
    ExposureLimitListResponse,
    # Exposure Tracking
    ExposureTrackingResponse,
    ExposureTrackingListResponse,
    # Summary
    BorrowingSummary,
    ALMGapAnalysis,
    ALMSummary,
    ExposureSummary,
    TreasurySummary,
)


__all__ = [
    # Entity/Borrower
    "EntityBase",
    "EntityCreate",
    "EntityUpdate",
    "EntityResponse",
    "EntityListResponse",
    "EntityDetailResponse",
    "EntityContactCreate",
    "EntityContactUpdate",
    "EntityContactResponse",
    "EntityAddressCreate",
    "EntityAddressUpdate",
    "EntityAddressResponse",
    "EntityBankAccountCreate",
    "EntityBankAccountUpdate",
    "EntityBankAccountResponse",
    "EntityRelationCreate",
    "EntityRelationUpdate",
    "EntityRelationResponse",
    "EntityFinancialCreate",
    "EntityFinancialUpdate",
    "EntityFinancialResponse",
    # KYC
    "KYCDocumentTypeCreate",
    "KYCDocumentTypeUpdate",
    "KYCDocumentTypeResponse",
    "EntityKYCDocumentCreate",
    "EntityKYCDocumentUpdate",
    "EntityKYCDocumentResponse",
    "CKYCSearchRequest",
    "CKYCDownloadRequest",
    "CKYCTransactionResponse",
    "BureauPullRequest",
    "BureauPullResponse",
    "BureauReportResponse",
    # Rating
    "RiskCategoryCreate",
    "RiskCategoryUpdate",
    "RiskCategoryResponse",
    "RiskParameterCreate",
    "RiskParameterUpdate",
    "RiskParameterResponse",
    "RatingMatrixCreate",
    "RatingMatrixUpdate",
    "RatingMatrixResponse",
    "EntityRatingCreate",
    "EntityRatingUpdate",
    "EntityRatingResponse",
    "EntityRatingDetailResponse",
    "RatingScoreDetailCreate",
    "RatingScoreDetailResponse",
    # Product
    "LoanProductCreate",
    "LoanProductUpdate",
    "LoanProductResponse",
    "LoanProductListResponse",
    "LoanProductDetailResponse",
    "InterestRateCreate",
    "InterestRateUpdate",
    "InterestRateResponse",
    "FeeMasterCreate",
    "FeeMasterUpdate",
    "FeeMasterResponse",
    "ProductFeeCreate",
    "ProductFeeUpdate",
    "ProductFeeResponse",
    "DocumentChecklistCreate",
    "DocumentChecklistUpdate",
    "DocumentChecklistResponse",
    # Application
    "LoanApplicationCreate",
    "LoanApplicationUpdate",
    "LoanApplicationResponse",
    "LoanApplicationListResponse",
    "LoanApplicationDetailResponse",
    "ApplicationDocumentCreate",
    "ApplicationDocumentUpdate",
    "ApplicationDocumentResponse",
    "ApplicationFeeCreate",
    "ApplicationFeeUpdate",
    "ApplicationFeeResponse",
    "TechnicalAppraisalCreate",
    "TechnicalAppraisalUpdate",
    "TechnicalAppraisalResponse",
    "FinancialAnalysisCreate",
    "FinancialAnalysisUpdate",
    "FinancialAnalysisResponse",
    "ProjectMilestoneCreate",
    "ProjectMilestoneUpdate",
    "ProjectMilestoneResponse",
    # Sanction
    "LoanSanctionCreate",
    "LoanSanctionUpdate",
    "LoanSanctionResponse",
    "LoanSanctionDetailResponse",
    "SanctionConditionCreate",
    "SanctionConditionUpdate",
    "SanctionConditionResponse",
    "LoanSecurityCreate",
    "LoanSecurityUpdate",
    "LoanSecurityResponse",
    # Phase 2: Loan Account
    "LoanAccountCreate",
    "LoanAccountUpdate",
    "LoanAccountResponse",
    "LoanAccountListResponse",
    "LoanAccountDetailResponse",
    # Disbursement
    "DisbursementCreate",
    "DisbursementUpdate",
    "DisbursementResponse",
    "DisbursementApproval",
    "DisbursementProcess",
    # Repayment Schedule
    "RepaymentScheduleCreate",
    "RepaymentScheduleResponse",
    "RepaymentScheduleDetailResponse",
    "ScheduleInstallmentResponse",
    # Loan Receipt
    "LoanReceiptCreate",
    "LoanReceiptUpdate",
    "LoanReceiptResponse",
    "LoanReceiptDetailResponse",
    "ReceiptAllocationCreate",
    "ReceiptAllocationResponse",
    "ReceiptBounceRequest",
    # Loan Mandate
    "LoanMandateCreate",
    "LoanMandateUpdate",
    "LoanMandateResponse",
    "MandateRegisterRequest",
    "MandateCancelRequest",
    # Asset Classification History
    "AssetClassificationHistoryCreate",
    "AssetClassificationHistoryResponse",
    # Loan Provision
    "LoanProvisionCreate",
    "LoanProvisionResponse",
    # Loan Adjustment
    "LoanAdjustmentCreate",
    "LoanAdjustmentResponse",
    # Accrual
    "LoanAccrualResponse",
    # Summary
    "LoanAccountSummary",
    "DPDBucket",
    "CollectionSummary",
    "DisbursementSummary",
    # Phase 3: NPA & Collections
    "CollectionFollowUpCreate",
    "CollectionFollowUpUpdate",
    "CollectionFollowUpExecute",
    "CollectionFollowUpResponse",
    "DemandNoticeCreate",
    "DemandNoticeUpdate",
    "DemandNoticeResponse",
    "NPARecordCreate",
    "NPARecordUpdate",
    "NPARecordResponse",
    "PenalInterestCreate",
    "PenalInterestResponse",
    "PenalWaiverCreate",
    "PenalWaiverApprove",
    "PenalWaiverResponse",
    "OTSProposalCreate",
    "OTSProposalUpdate",
    "OTSProposalApprove",
    "OTSBorrowerAccept",
    "OTSPaymentScheduleCreate",
    "OTSPaymentScheduleResponse",
    "OTSProposalResponse",
    "LoanRestructureCreate",
    "LoanRestructureUpdate",
    "LoanRestructureApprove",
    "LoanRestructureImplement",
    "LoanRestructureResponse",
    "LegalCaseCreate",
    "LegalCaseUpdate",
    "LegalCaseResponse",
    "LegalHearingCreate",
    "LegalHearingUpdate",
    "LegalHearingResponse",
    "PropertyAuctionCreate",
    "PropertyAuctionUpdate",
    "PropertyAuctionResponse",
    "WriteOffCreate",
    "WriteOffApprove",
    "WriteOffEffect",
    "WriteOffResponse",
    "NPASummary",
    "CollectionActivitySummary",
    "RecoverySummary",
    "PaginatedFollowUpResponse",
    "PaginatedDemandNoticeResponse",
    "PaginatedNPARecordResponse",
    "PaginatedOTSProposalResponse",
    "PaginatedRestructureResponse",
    "PaginatedLegalCaseResponse",
    "PaginatedAuctionResponse",
    "PaginatedWriteOffResponse",
    # Phase 4: Treasury & ALM
    "LenderCreate",
    "LenderUpdate",
    "LenderResponse",
    "LenderListResponse",
    "BorrowingCreate",
    "BorrowingUpdate",
    "BorrowingResponse",
    "BorrowingListResponse",
    "BorrowingDetailResponse",
    "BorrowingTrancheCreate",
    "BorrowingTrancheApprove",
    "BorrowingTrancheDisbursement",
    "BorrowingTrancheResponse",
    "BorrowingTrancheListResponse",
    "BorrowingScheduleResponse",
    "BorrowingScheduleListResponse",
    "BorrowingPaymentCreate",
    "BorrowingPaymentResponse",
    "BorrowingPaymentListResponse",
    "BorrowingCovenantCreate",
    "BorrowingCovenantUpdate",
    "BorrowingCovenantResponse",
    "BorrowingCovenantListResponse",
    "ALMPositionGenerate",
    "ALMPositionResponse",
    "ALMPositionListResponse",
    "ALMPositionDetailResponse",
    "ALMAssetResponse",
    "ALMLiabilityResponse",
    "IRSAnalysisGenerate",
    "IRSAnalysisResponse",
    "IRSAnalysisListResponse",
    "ExposureLimitCreate",
    "ExposureLimitUpdate",
    "ExposureLimitResponse",
    "ExposureLimitListResponse",
    "ExposureTrackingResponse",
    "ExposureTrackingListResponse",
    "BorrowingSummary",
    "ALMGapAnalysis",
    "ALMSummary",
    "ExposureSummary",
    "TreasurySummary",
    # Phase 5: NACH Integration
    "NachBatchBase",
    "NachBatchCreate",
    "NachBatchGenerateRequest",
    "NachBatchUpdate",
    "NachBatchSubmit",
    "NachBatchResponseUpload",
    "NachBatchResponse",
    "NachBatchDetailResponse",
    "NachBatchListResponse",
    "NachTransactionBase",
    "NachTransactionCreate",
    "NachTransactionUpdate",
    "NachTransactionBulkStatusUpdate",
    "NachTransactionResponse",
    "NachTransactionDetailResponse",
    "NachTransactionListResponse",
    "NachTransactionSummary",
    "NachMandateLogCreate",
    "NachMandateLogUpdate",
    "NachMandateLogResponse",
    "MandateRegistrationRequest",
    "MandateRegistrationResponse",
    "MandateCancellationRequest",
    "NachBatchStatistics",
    "NachMonthlyReport",
    "NachBounceAnalysis",
    "NachRetryDue",
    "NachRetryDueList",
    "NachFileGenerationRequest",
    "NachFileGenerationResponse",
    "NachResponseFileParseRequest",
    "NachResponseFileParseResponse",
    # Phase 6: Account Aggregator Integration
    "AAConsentBase",
    "AAConsentCreate",
    "AAConsentUpdate",
    "AAConsentResponse",
    "AAConsentDetailResponse",
    "AAConsentListResponse",
    "AAConsentRequestInitiate",
    "AAConsentInitiateResponse",
    "AAConsentRevokeRequest",
    "AAFetchSessionBase",
    "AAFetchSessionCreate",
    "AAFetchSessionUpdate",
    "AAFetchSessionResponse",
    "AAFetchSessionDetailResponse",
    "AAFetchSessionListResponse",
    "AAFetchDataRequest",
    "AAFetchDataResponse",
    "AABankAccountBase",
    "AABankAccountCreate",
    "AABankAccountResponse",
    "AABankAccountDetailResponse",
    "AABankAccountListResponse",
    "AABankTransactionBase",
    "AABankTransactionCreate",
    "AABankTransactionResponse",
    "AABankTransactionListResponse",
    "AAConsentLogBase",
    "AAConsentLogCreate",
    "AAConsentLogResponse",
    "AAConsentLogListResponse",
    "AAConsentStatistics",
    "AAFetchStatistics",
    "AABankStatementAnalysis",
    "AADataImportRequest",
    "AADataImportResponse",
    "AAProviderConfig",
    "AAProviderHealthCheck",
    "AAWebhookNotification",
    "AAConsentStatusWebhook",
    "AAFINotificationWebhook",
]
