"""Increase account_group code column size

Revision ID: 74c88413b1e7
Revises: b66f36966954
Create Date: 2026-01-11 21:28:30.135007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c88413b1e7'
down_revision: Union[str, None] = 'b66f36966954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mst_account_group', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_comment='Group code e.g. ASSETS, CURRENT_ASSETS',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mst_account_group', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_comment='Group code e.g. ASSETS, CURRENT_ASSETS',
               existing_nullable=False)
    # ### end Alembic commands ###
