"""Add finance models

Revision ID: b66f36966954
Revises: 
Create Date: 2026-01-11 21:24:20.161458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b66f36966954'
down_revision: Union[str, None] = 'a0000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_account_group',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Group code e.g. ASSETS, CURRENT_ASSETS'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Group name e.g. Current Assets'),
    sa.Column('nature', sa.Enum('ASSETS', 'LIABILITIES', 'INCOME', 'EXPENSES', 'EQUITY', name='accountnature'), nullable=False, comment='Account nature - ASSETS, LIABILITIES, INCOME, EXPENSES, EQUITY'),
    sa.Column('parent_group_id', sa.UUID(), nullable=True, comment='Parent account group for hierarchy'),
    sa.Column('level', sa.Integer(), nullable=False, comment='Hierarchy level (0 for root)'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='Materialized path for hierarchy e.g. /uuid1/uuid2/'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Display order within parent'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System-defined group (cannot be deleted)'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_group_id'], ['mst_account_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_account_group_code'), 'mst_account_group', ['code'], unique=False)
    op.create_index(op.f('ix_mst_account_group_organization_id'), 'mst_account_group', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mst_account_group_parent_group_id'), 'mst_account_group', ['parent_group_id'], unique=False)
    op.create_table('mst_financial_year',
    sa.Column('code', sa.String(length=20), nullable=False, comment='FY code e.g. FY2024-25'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name e.g. April 2024 - March 2025'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Financial year start date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Financial year end date'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='Is this the current active financial year'),
    sa.Column('is_closed', sa.Boolean(), nullable=False, comment='Is this financial year closed'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='When the year was closed'),
    sa.Column('closed_by', sa.UUID(), nullable=True, comment='User who closed the year'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_financial_year_code'), 'mst_financial_year', ['code'], unique=True)
    op.create_index(op.f('ix_mst_financial_year_organization_id'), 'mst_financial_year', ['organization_id'], unique=False)
    op.create_table('mst_voucher_type',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Voucher type code e.g. JV, PV, RV, CV'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name e.g. Journal Voucher, Payment Voucher'),
    sa.Column('voucher_class', sa.Enum('JOURNAL', 'PAYMENT', 'RECEIPT', 'CONTRA', 'SALES', 'PURCHASE', name='voucherclass'), nullable=False, comment='Classification - JOURNAL, PAYMENT, RECEIPT, CONTRA, SALES, PURCHASE'),
    sa.Column('prefix', sa.String(length=20), nullable=False, comment='Voucher number prefix e.g. JV-, PV-'),
    sa.Column('auto_numbering', sa.Boolean(), nullable=False, comment='Auto-generate voucher numbers'),
    sa.Column('starting_number', sa.Integer(), nullable=False, comment='Starting number for auto-numbering'),
    sa.Column('current_number', sa.Integer(), nullable=False, comment='Last used number'),
    sa.Column('number_format', sa.String(length=50), nullable=True, comment='Number format pattern e.g. {PREFIX}{YEAR}-{NUMBER:05d}'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='Requires approval workflow'),
    sa.Column('approval_levels', sa.Integer(), nullable=False, comment='Number of approval levels required'),
    sa.Column('default_narration', sa.String(length=500), nullable=True, comment='Default narration template'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System-defined type (cannot be deleted)'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_voucher_type_code'), 'mst_voucher_type', ['code'], unique=False)
    op.create_index(op.f('ix_mst_voucher_type_organization_id'), 'mst_voucher_type', ['organization_id'], unique=False)
    op.create_table('mst_account',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Account code e.g. 1001, 2001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Account name e.g. Cash in Hand, Trade Payables'),
    sa.Column('account_group_id', sa.UUID(), nullable=False, comment='Parent account group'),
    sa.Column('account_type', sa.Enum('GROUP', 'LEDGER', 'BANK', 'CASH', 'CONTROL', name='accounttype'), nullable=False, comment='Type of account - GROUP, LEDGER, BANK, CASH, CONTROL'),
    sa.Column('is_control_account', sa.Boolean(), nullable=False, comment='Is this a control account for sub-ledger'),
    sa.Column('control_type', sa.Enum('CUSTOMER', 'VENDOR', 'BANK', 'EMPLOYEE', name='controlaccounttype'), nullable=True, comment='Type of control account if is_control_account is True'),
    sa.Column('currency_code', sa.String(length=3), nullable=False, comment='Currency code ISO 4217'),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='Opening balance amount'),
    sa.Column('opening_balance_type', sa.Enum('DEBIT', 'CREDIT', name='balancetype'), nullable=True, comment='Opening balance type DR/CR'),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='Current running balance'),
    sa.Column('current_balance_type', sa.Enum('DEBIT', 'CREDIT', name='balancetype'), nullable=True, comment='Current balance type DR/CR'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True, comment='GSTIN if applicable'),
    sa.Column('pan', sa.String(length=10), nullable=True, comment='PAN if applicable'),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False, comment='Is TDS applicable on this account'),
    sa.Column('tds_section', sa.String(length=20), nullable=True, comment='Default TDS section code'),
    sa.Column('is_bank_account', sa.Boolean(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('is_cash_account', sa.Boolean(), nullable=False),
    sa.Column('allow_negative_balance', sa.Boolean(), nullable=False),
    sa.Column('is_reconciliation_required', sa.Boolean(), nullable=False, comment='Is bank reconciliation required for this account'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System-defined account (cannot be deleted)'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_group_id'], ['mst_account_group.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_account_account_group_id'), 'mst_account', ['account_group_id'], unique=False)
    op.create_index(op.f('ix_mst_account_code'), 'mst_account', ['code'], unique=False)
    op.create_index(op.f('ix_mst_account_organization_id'), 'mst_account', ['organization_id'], unique=False)
    op.create_table('mst_financial_period',
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False, comment='Period number 1-12 (or 13 for adjustment period)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Period name e.g. April 2024'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('is_adjustment_period', sa.Boolean(), nullable=False, comment='Is this the year-end adjustment period'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['mst_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_financial_period_financial_year_id'), 'mst_financial_period', ['financial_year_id'], unique=False)
    op.create_table('txn_voucher',
    sa.Column('voucher_type_id', sa.UUID(), nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False, comment='Auto-generated or manual voucher number'),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='External reference number'),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True, comment='Voucher narration/description'),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED', name='voucherstatus'), nullable=False),
    sa.Column('approval_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Approval workflow status [{level, approved_by, approved_at}]'),
    sa.Column('current_approval_level', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversal_voucher_id', sa.UUID(), nullable=True),
    sa.Column('original_voucher_id', sa.UUID(), nullable=True, comment='If this is a reversal, reference to original voucher'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['mst_financial_year.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_voucher_id'], ['txn_voucher.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['mst_financial_period.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversal_voucher_id'], ['txn_voucher.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['mst_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_type_id'], ['mst_voucher_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_txn_voucher_financial_year_id'), 'txn_voucher', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_txn_voucher_organization_id'), 'txn_voucher', ['organization_id'], unique=False)
    op.create_index(op.f('ix_txn_voucher_period_id'), 'txn_voucher', ['period_id'], unique=False)
    op.create_index(op.f('ix_txn_voucher_status'), 'txn_voucher', ['status'], unique=False)
    op.create_index(op.f('ix_txn_voucher_unit_id'), 'txn_voucher', ['unit_id'], unique=False)
    op.create_index(op.f('ix_txn_voucher_voucher_date'), 'txn_voucher', ['voucher_date'], unique=False)
    op.create_index(op.f('ix_txn_voucher_voucher_number'), 'txn_voucher', ['voucher_number'], unique=False)
    op.create_index(op.f('ix_txn_voucher_voucher_type_id'), 'txn_voucher', ['voucher_type_id'], unique=False)
    op.create_table('txn_voucher_line',
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False, comment='Line sequence number'),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True, comment='Line-level narration'),
    sa.Column('cost_center_id', sa.UUID(), nullable=True, comment='Cost center for expense allocation'),
    sa.Column('party_type', sa.Enum('CUSTOMER', 'VENDOR', 'EMPLOYEE', name='partytype'), nullable=True, comment='Type of party - CUSTOMER, VENDOR, EMPLOYEE'),
    sa.Column('party_id', sa.UUID(), nullable=True, comment='Party ID for sub-ledger'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='Reference document type e.g. INVOICE, BILL'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='Reference document ID'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Reference document number'),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mst_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['txn_voucher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_txn_voucher_line_account_id'), 'txn_voucher_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_txn_voucher_line_voucher_id'), 'txn_voucher_line', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_txn_voucher_line_voucher_id'), table_name='txn_voucher_line')
    op.drop_index(op.f('ix_txn_voucher_line_account_id'), table_name='txn_voucher_line')
    op.drop_table('txn_voucher_line')
    op.drop_index(op.f('ix_txn_voucher_voucher_type_id'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_voucher_number'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_voucher_date'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_unit_id'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_status'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_period_id'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_organization_id'), table_name='txn_voucher')
    op.drop_index(op.f('ix_txn_voucher_financial_year_id'), table_name='txn_voucher')
    op.drop_table('txn_voucher')
    op.drop_index(op.f('ix_mst_financial_period_financial_year_id'), table_name='mst_financial_period')
    op.drop_table('mst_financial_period')
    op.drop_index(op.f('ix_mst_account_organization_id'), table_name='mst_account')
    op.drop_index(op.f('ix_mst_account_code'), table_name='mst_account')
    op.drop_index(op.f('ix_mst_account_account_group_id'), table_name='mst_account')
    op.drop_table('mst_account')
    op.drop_index(op.f('ix_mst_voucher_type_organization_id'), table_name='mst_voucher_type')
    op.drop_index(op.f('ix_mst_voucher_type_code'), table_name='mst_voucher_type')
    op.drop_table('mst_voucher_type')
    op.drop_index(op.f('ix_mst_financial_year_organization_id'), table_name='mst_financial_year')
    op.drop_index(op.f('ix_mst_financial_year_code'), table_name='mst_financial_year')
    op.drop_table('mst_financial_year')
    op.drop_index(op.f('ix_mst_account_group_parent_group_id'), table_name='mst_account_group')
    op.drop_index(op.f('ix_mst_account_group_organization_id'), table_name='mst_account_group')
    op.drop_index(op.f('ix_mst_account_group_code'), table_name='mst_account_group')
    op.drop_table('mst_account_group')
    # ### end Alembic commands ###
