"""Add GST and TDS tables

Revision ID: bd17a32dbbd4
Revises: 4aeb501e0e8c
Create Date: 2026-01-11 22:07:13.611191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd17a32dbbd4'
down_revision: Union[str, None] = '4aeb501e0e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_gst_rate',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Rate code e.g. GST0, GST5, GST12, GST18, GST28'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Rate name e.g. GST 18%'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Description of the rate applicability'),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total GST rate percentage'),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Central GST rate (intra-state)'),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='State GST rate (intra-state)'),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Integrated GST rate (inter-state)'),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Compensation cess rate'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Rate effective from date'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Rate effective to date (null = currently active)'),
    sa.Column('is_composition', sa.Boolean(), nullable=False, comment='Is this a composition scheme rate'),
    sa.Column('is_reverse_charge', sa.Boolean(), nullable=False, comment='Is this applicable for reverse charge'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_gst_rate_code'), 'mst_gst_rate', ['code'], unique=True)
    op.create_table('mst_gst_registration',
    sa.Column('gstin', sa.String(length=15), nullable=False, comment='15-digit GSTIN number'),
    sa.Column('legal_name', sa.String(length=200), nullable=False, comment='Legal name as per GST registration'),
    sa.Column('trade_name', sa.String(length=200), nullable=True, comment='Trade name / business name'),
    sa.Column('registration_type', sa.Enum('REGULAR', 'COMPOSITION', 'SEZ', 'DEEMED_EXPORT', 'CASUAL', 'NON_RESIDENT', 'UNREGISTERED', name='gstregistrationtype'), nullable=False, comment='Type of GST registration'),
    sa.Column('state_code', sa.String(length=2), nullable=False, comment='2-digit state code from GSTIN'),
    sa.Column('state_name', sa.String(length=50), nullable=False, comment='State name'),
    sa.Column('address', sa.Text(), nullable=True, comment='Registered address'),
    sa.Column('pincode', sa.String(length=6), nullable=True, comment='PIN code'),
    sa.Column('is_e_invoice_enabled', sa.Boolean(), nullable=False, comment='E-Invoice enabled for this GSTIN'),
    sa.Column('e_invoice_username', sa.String(length=100), nullable=True, comment='E-Invoice portal username'),
    sa.Column('e_invoice_password_encrypted', sa.String(length=500), nullable=True, comment='Encrypted E-Invoice portal password'),
    sa.Column('is_e_way_bill_enabled', sa.Boolean(), nullable=False, comment='E-Way Bill enabled for this GSTIN'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit specific GSTIN (for branches)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['mst_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_gst_registration_gstin'), 'mst_gst_registration', ['gstin'], unique=True)
    op.create_index(op.f('ix_mst_gst_registration_organization_id'), 'mst_gst_registration', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mst_gst_registration_unit_id'), 'mst_gst_registration', ['unit_id'], unique=False)
    op.create_table('mst_tds_section',
    sa.Column('section_code', sa.String(length=20), nullable=False, comment='Section code e.g. 194C, 194J, 194I'),
    sa.Column('section_name', sa.String(length=200), nullable=False, comment='Section description'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of applicability'),
    sa.Column('rate_individual', sa.Numeric(precision=5, scale=2), nullable=False, comment='Rate for Individual/HUF with PAN'),
    sa.Column('rate_company', sa.Numeric(precision=5, scale=2), nullable=False, comment='Rate for Company with PAN'),
    sa.Column('rate_no_pan', sa.Numeric(precision=5, scale=2), nullable=False, comment='Rate when PAN not available'),
    sa.Column('rate_lower_deduction', sa.Numeric(precision=5, scale=2), nullable=True, comment='Lower deduction rate if applicable'),
    sa.Column('threshold_single', sa.Numeric(precision=18, scale=2), nullable=False, comment='Single transaction threshold'),
    sa.Column('threshold_annual', sa.Numeric(precision=18, scale=2), nullable=False, comment='Annual aggregate threshold'),
    sa.Column('is_tcs', sa.Boolean(), nullable=False, comment='Is this a TCS section (not TDS)'),
    sa.Column('surcharge_applicable', sa.Boolean(), nullable=False, comment='Is surcharge applicable'),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Health & Education Cess rate'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Section effective from date'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Section effective to date (null = currently active)'),
    sa.Column('return_form', sa.String(length=10), nullable=False, comment='TDS return form - 24Q, 26Q, 27Q, 27EQ'),
    sa.Column('nature_of_payment_code', sa.String(length=10), nullable=True, comment='Code for TDS return filing'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_tds_section_section_code'), 'mst_tds_section', ['section_code'], unique=True)
    op.create_table('mst_hsn_sac',
    sa.Column('code', sa.String(length=20), nullable=False, comment='HSN/SAC code e.g. 8471, 998314'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of goods/services'),
    sa.Column('hsn_sac_type', sa.Enum('HSN', 'SAC', name='hsnsactype'), nullable=False, comment='Type - HSN for goods, SAC for services'),
    sa.Column('chapter', sa.String(length=10), nullable=True, comment='HSN chapter number'),
    sa.Column('section', sa.String(length=10), nullable=True, comment='HSN section'),
    sa.Column('gst_rate_id', sa.UUID(), nullable=True, comment='Default GST rate for this HSN/SAC'),
    sa.Column('unit_of_measurement', sa.String(length=20), nullable=True, comment='Default UOM e.g. NOS, KGS, MTR'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gst_rate_id'], ['mst_gst_rate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_hsn_sac_code'), 'mst_hsn_sac', ['code'], unique=True)
    op.create_table('txn_tds_entry',
    sa.Column('tds_section_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=True, comment='Source voucher for this TDS entry'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('deductee_name', sa.String(length=200), nullable=False, comment='Name of deductee (vendor/party)'),
    sa.Column('deductee_pan', sa.String(length=10), nullable=True, comment='PAN of deductee'),
    sa.Column('deductee_type', sa.Enum('INDIVIDUAL', 'HUF', 'COMPANY', 'FIRM', 'AOP_BOI', 'LOCAL_AUTHORITY', 'GOVERNMENT', 'TRUST', 'FOREIGN_COMPANY', name='tdsdeducteetype'), nullable=False),
    sa.Column('deductee_address', sa.Text(), nullable=True),
    sa.Column('deduction_date', sa.Date(), nullable=False, comment='Date of TDS deduction'),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Amount on which TDS is calculated'),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='TDS rate applied'),
    sa.Column('tds_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Basic TDS amount'),
    sa.Column('surcharge', sa.Numeric(precision=18, scale=2), nullable=False, comment='Surcharge amount'),
    sa.Column('cess', sa.Numeric(precision=18, scale=2), nullable=False, comment='Health & Education Cess'),
    sa.Column('total_tds', sa.Numeric(precision=18, scale=2), nullable=False, comment='Total TDS = TDS + Surcharge + Cess'),
    sa.Column('lower_deduction_cert_no', sa.String(length=50), nullable=True, comment='Lower deduction certificate number'),
    sa.Column('challan_status', sa.Enum('PENDING', 'PAID', 'VERIFIED', name='tdschallanstatus'), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=True, comment='BSR/Challan number after payment'),
    sa.Column('challan_date', sa.Date(), nullable=True, comment='Date of TDS deposit'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Bank through which TDS deposited'),
    sa.Column('bsr_code', sa.String(length=10), nullable=True, comment='BSR code of the bank'),
    sa.Column('certificate_number', sa.String(length=50), nullable=True, comment='TDS certificate number (Form 16/16A)'),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('return_quarter', sa.String(length=10), nullable=True, comment='Quarter for return e.g. Q1, Q2, Q3, Q4'),
    sa.Column('return_filed', sa.Boolean(), nullable=False, comment='Is TDS return filed for this entry'),
    sa.Column('acknowledgment_number', sa.String(length=50), nullable=True, comment='TDS return acknowledgment number'),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['mst_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tds_section_id'], ['mst_tds_section.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['mst_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['txn_voucher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_txn_tds_entry_deduction_date'), 'txn_tds_entry', ['deduction_date'], unique=False)
    op.create_index(op.f('ix_txn_tds_entry_organization_id'), 'txn_tds_entry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_txn_tds_entry_tds_section_id'), 'txn_tds_entry', ['tds_section_id'], unique=False)
    op.create_index(op.f('ix_txn_tds_entry_voucher_id'), 'txn_tds_entry', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_txn_tds_entry_voucher_id'), table_name='txn_tds_entry')
    op.drop_index(op.f('ix_txn_tds_entry_tds_section_id'), table_name='txn_tds_entry')
    op.drop_index(op.f('ix_txn_tds_entry_organization_id'), table_name='txn_tds_entry')
    op.drop_index(op.f('ix_txn_tds_entry_deduction_date'), table_name='txn_tds_entry')
    op.drop_table('txn_tds_entry')
    op.drop_index(op.f('ix_mst_hsn_sac_code'), table_name='mst_hsn_sac')
    op.drop_table('mst_hsn_sac')
    op.drop_index(op.f('ix_mst_tds_section_section_code'), table_name='mst_tds_section')
    op.drop_table('mst_tds_section')
    op.drop_index(op.f('ix_mst_gst_registration_unit_id'), table_name='mst_gst_registration')
    op.drop_index(op.f('ix_mst_gst_registration_organization_id'), table_name='mst_gst_registration')
    op.drop_index(op.f('ix_mst_gst_registration_gstin'), table_name='mst_gst_registration')
    op.drop_table('mst_gst_registration')
    op.drop_index(op.f('ix_mst_gst_rate_code'), table_name='mst_gst_rate')
    op.drop_table('mst_gst_rate')
    # ### end Alembic commands ###
