"""Portal-side request/response schemas."""

from app.schemas.portal.admin_user import (
    AdminPortalInviteResponse,
    AdminPortalUserCreateRequest,
    AdminPortalUserDetail,
    AdminPortalUserEntityLink,
    AdminPortalUserListItem,
    AdminPortalUserListResponse,
    AdminPortalUserUpdateRequest,
)
from app.schemas.portal.application import (
    ApplicationDetailResponse,
    ApplicationDocumentResponse,
    ApplicationListItem,
    ApplicationListResponse,
    ApplicationStatusEvent,
    CreateApplicationRequest,
    FundUtilizationLine,
    ProductListItem,
    UpdateApplicationRequest,
    UploadDocumentResponse,
    UtilizationCategoryListItem,
)
from app.schemas.portal.claim import (
    BorrowerClaimCreateRequest,
    BorrowerClaimDocument,
    BorrowerClaimEnrollmentItem,
    BorrowerClaimEnrollmentListResponse,
    BorrowerClaimItem,
    BorrowerClaimListResponse,
    BorrowerClaimStats,
    BorrowerClaimSubmitRequest,
    BorrowerClaimsWorkbenchResponse,
    BorrowerEligibleClaimPeriod,
    BorrowerEligibleClaimPeriodsResponse,
)
from app.schemas.portal.registration import (
    AdminRegistrationDetail,
    AdminRegistrationListItem,
    AdminRegistrationListResponse,
    ApproveRequest,
    EntitySuggestion,
    RegisterRequest,
    RegisterResponse,
    RegisterVerifyOtpRequest,
    RegisterVerifyOtpResponse,
    RegistrationStatusResponse,
    RejectRequest,
)
from app.schemas.portal.reporting import (
    PortalReportApplicationSummary,
    PortalReportBorrowerBreakdownItem,
    PortalReportClaimSummary,
    PortalReportingResponse,
    PortalReportRecentReleaseItem,
    PortalReportReviewBreakdownItem,
    PortalReportStatusBreakdownItem,
)
from app.schemas.portal.workbench import (
    PortalWorkbenchResponse,
    WorkbenchAction,
    WorkbenchApplication,
    WorkbenchStat,
)

__all__ = [
    # Registration
    "AdminRegistrationDetail",
    "AdminRegistrationListItem",
    "AdminRegistrationListResponse",
    "ApproveRequest",
    "EntitySuggestion",
    "RegisterRequest",
    "RegisterResponse",
    "RegisterVerifyOtpRequest",
    "RegisterVerifyOtpResponse",
    "RegistrationStatusResponse",
    "RejectRequest",
    # Application
    "ApplicationDetailResponse",
    "ApplicationDocumentResponse",
    "ApplicationListItem",
    "ApplicationListResponse",
    "ApplicationStatusEvent",
    "CreateApplicationRequest",
    "FundUtilizationLine",
    "ProductListItem",
    "UpdateApplicationRequest",
    "UploadDocumentResponse",
    "UtilizationCategoryListItem",
    # Workbench
    "PortalWorkbenchResponse",
    "WorkbenchAction",
    "WorkbenchApplication",
    "WorkbenchStat",
    # Claims
    "BorrowerClaimCreateRequest",
    "BorrowerClaimDocument",
    "BorrowerClaimEnrollmentItem",
    "BorrowerClaimEnrollmentListResponse",
    "BorrowerClaimItem",
    "BorrowerClaimListResponse",
    "BorrowerClaimsWorkbenchResponse",
    "BorrowerClaimStats",
    "BorrowerClaimSubmitRequest",
    "BorrowerEligibleClaimPeriod",
    "BorrowerEligibleClaimPeriodsResponse",
    # Admin portal users
    "AdminPortalInviteResponse",
    "AdminPortalUserCreateRequest",
    "AdminPortalUserDetail",
    "AdminPortalUserEntityLink",
    "AdminPortalUserListItem",
    "AdminPortalUserListResponse",
    "AdminPortalUserUpdateRequest",
    # Reporting
    "PortalReportApplicationSummary",
    "PortalReportBorrowerBreakdownItem",
    "PortalReportClaimSummary",
    "PortalReportRecentReleaseItem",
    "PortalReportReviewBreakdownItem",
    "PortalReportingResponse",
    "PortalReportStatusBreakdownItem",
]
