"""BI/Analytics schemas package."""

from app.schemas.bi.datasource import (
    DataSourceBase,
    DataSourceCreate,
    DataSourceUpdate,
    DataSourceResponse,
    DataSourceListResponse,
    DataSourceFetchRequest,
    DataSourceFetchResponse,
)
from app.schemas.bi.chart import (
    ChartRoleAccessBase,
    ChartRoleAccessCreate,
    ChartRoleAccessResponse,
    ChartDefinitionBase,
    ChartDefinitionCreate,
    ChartDefinitionUpdate,
    ChartDefinitionResponse,
    ChartDefinitionListResponse,
    SetChartRoleAccessRequest,
)
from app.schemas.bi.dashboard import (
    DashboardWidgetBase,
    DashboardWidgetCreate,
    DashboardWidgetUpdate,
    DashboardWidgetLayoutUpdate,
    BulkLayoutUpdateRequest,
    DashboardWidgetResponse,
    DashboardRoleAccessBase,
    DashboardRoleAccessCreate,
    DashboardRoleAccessUpdate,
    DashboardRoleAccessResponse,
    DashboardBase,
    DashboardCreate,
    DashboardUpdate,
    DashboardResponse,
    DashboardListResponse,
    LandingDashboardResponse,
)

__all__ = [
    # Data Source
    "DataSourceBase",
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    "DataSourceListResponse",
    "DataSourceFetchRequest",
    "DataSourceFetchResponse",
    # Chart Definition
    "ChartRoleAccessBase",
    "ChartRoleAccessCreate",
    "ChartRoleAccessResponse",
    "ChartDefinitionBase",
    "ChartDefinitionCreate",
    "ChartDefinitionUpdate",
    "ChartDefinitionResponse",
    "ChartDefinitionListResponse",
    "SetChartRoleAccessRequest",
    # Dashboard
    "DashboardWidgetBase",
    "DashboardWidgetCreate",
    "DashboardWidgetUpdate",
    "DashboardWidgetLayoutUpdate",
    "BulkLayoutUpdateRequest",
    "DashboardWidgetResponse",
    "DashboardRoleAccessBase",
    "DashboardRoleAccessCreate",
    "DashboardRoleAccessUpdate",
    "DashboardRoleAccessResponse",
    "DashboardBase",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardResponse",
    "DashboardListResponse",
    "LandingDashboardResponse",
]
